### ISSUE TITLE
Wrong import in youtube_api.py

### ISSUE THREAD

**Issue by antonioarbues** [jpetzke/AutoGPT-YouTube#1]
Need to apply the following git diff to make it work.
I don't have rights to open a PR unfortunately :/

`-from . import AutoGPTYouTube
+from . import AutoGPT_YouTube
 import requests
 
-plugin = AutoGPTYouTube()
+plugin = AutoGPT_YouTube()`

**Comment by MCFoxyDev** [comment]
Thanks you helped me a lot!

**Comment by antonioarbues** [comment]
> @antonioarbues you say that you cannot create a pull request. How do I allow anyone to create a pull request?

I guess it's in the repo setting - don't know exactly

**Comment by jpetzke** [comment]
> I guess it's in the repo setting - don't know exactly

You have to fork the repo first in order to create a pull requests. 
#2
