### ISSUE TITLE
update Readme.md for ffmpeg installation

### ISSUE THREAD

**Issue by rabbyn** [jpetzke/AutoGPT-YouTube#10]
Hello @jpetzke , thanks for your plugin ! it works ! I just struggled a bit to understand that I had to install ffmpeg on my machine. Maybe you could add a paragraph for that on your Readme.md for user which are not familiar with python (like me :p ) . Thanks

**ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error**

PS: is the file downloaded suppose to be in webm format ? or can it be converted to mp4 with some sort of options ?

**Comment by jpetzke** [comment]
Added.

It is possible to further specify the format, but not necessarily needed.
