### ISSUE TITLE
Bug?: Unable to transcribe videos

### ISSUE THREAD

**Issue by BaseInfinity** [jpetzke/AutoGPT-YouTube#12]
I get stuck in this loop where ffmpeg is installed but the command `download_youtube_video`  keeps saying I don't.

Then it runs `which ffmpeg` and realizes it is installed, and then tries to do the `download_youtube_video` command again...

repeats the cycle cuz it still thinks `ffmpeg` isnt installed. I'm on a M1 if that makes any difference.

ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error

<img width="1620" alt="Screen Shot 2023-05-04 at 7 57 27 PM" src="https://user-images.githubusercontent.com/1424113/236368998-9416a44c-3773-499d-bf75-19798f98342f.png">

**Comment by jpetzke** [comment]
Are all ffmpeg executables in your PATH/Env? Try running `ffmpeg --version` from a normal console window

**Comment by BaseInfinity** [comment]
@jpetzke thanks for the hint, you were totes right, I somehow had all of my dependencies unlinked @.@

Relinked them with:
`brew link --overwrite $(brew list)`

And it worked, thanks! I'll go ahead and close this issue
