### ISSUE TITLE
Bug?: get_youtube_comments seems to choke?

### ISSUE THREAD

**Issue by BaseInfinity** [jpetzke/AutoGPT-YouTube#13]
I'm having a hard time completing this task, anyone else have better luck?

<img width="1500" alt="Screen Shot 2023-05-04 at 8 14 47 PM" src="https://user-images.githubusercontent.com/1424113/236370677-fe36a2be-a9da-4b10-adda-a379135759a2.png">

I'm on Mac M1 if that matters

**Comment by jpetzke** [comment]
I don't think that this is the fault of this plugin. View the communication log and see what the request actually contained
