### ISSUE TITLE
Couldn't find ffmpeg or avconv

### ISSUE THREAD

**Issue by KlarwasserX** [jpetzke/AutoGPT-YouTube#15]
Im running auto-gpt in docker (installed it like described in the docs). But when im trying to download video footage from Youtube i always get this error:

/usr/local/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

[youtube] cR8GVePOdpY: Downloading webpage
[youtube] cR8GVePOdpY: Downloading android player API JSON
[youtube] cR8GVePOdpY: Downloading tv embedded player API JSON
[youtube] cR8GVePOdpY: Downloading web embedded client config
[youtube] cR8GVePOdpY: Downloading player 50cf60f0
[youtube] cR8GVePOdpY: Downloading web embedded player API JSON
[info] cR8GVePOdpY: Downloading 1 format(s): 315+251
ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
SYSTEM:  Command download_youtube_video returned: Error: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error

**Comment by jpetzke** [comment]
You need to install ffmpeg in your docker
