### ISSUE TITLE
Auto-GPT not triggerting YT plugin

### ISSUE THREAD

**Issue by solo2424** [jpetzke/AutoGPT-YouTube#19]
So I installed the plugin based on instructions, provided my API key in the .env. When I boot up it asks me if I want to allow the YT plugin and I answer "y" (I will later add to allowed list once I no it is loading and working properly) 

I give a simple goal to search and download a video. I do a second goal "remember to use the AutoGPT_YouTube plugin" I get a lot of random attempts, but none seem to be using the plugins. I get errors such as 

1.) 
Error:
  Attempted to access absolute path 'C:\Users\jerem\AI_Projects\Auto-GPT\plugins\AutoGPT-YouTube' in workspace 'C:\Users\jerem\AI_Projects\Auto-GPT\autogpt\auto_gpt_workspace'.

2.)
Error:
  Attempted to access absolute path 'C:\Users\jerem\AI_Projects\Auto-GPT\plugins\AutoGPT-YouTube\AutoGPT_YouTube.py' in workspace 'C:\Users\jerem\AI_Projects\Auto-GPT\autogpt\auto_gpt_workspace'.

3.)
Executing command 'cd C:\Users\jerem\AI_Projects\Auto-GPT\autogpt\auto_gpt_workspace && python AutoGPT_YouTube.py --search_query 'try not to laugh' --num_videos 10 --output_folder videos' in working directory 'C:\Users\jerem\AI_Projects\Auto-GPT\autogpt\auto_gpt_workspace'

python AutoGPT_YouTube.py is not in the workspace folder so this leave me to believe it is not attempting to use the plugin.

Am I missing something? Is there a trick to make sure it uses the plugin?

**Comment by solo2424** [comment]
I believe this issue has been resolved. It may have been a 3 part issue. 

First, I did not have my Youtube API key in the .env file.
Second, I did not have the YoutTube Data V3 API enabled on my account
Third, (Not fully tested but think this could be an issue) I was tellin itto use "AutoGPT_YouTube" plugin, but had success when I told it to use the "AutoGPT-YouTube" plugin.

**Comment by solo2424** [comment]
I beleive I spoke too soon. It still seem to not want to use the youtube plugin consistently.

NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'filename': 'C:\\Users\\jerem\\AI_Projects\\Auto-GPT\\autogpt\\auto_gpt_workspace\\autogpt\\auto_gpt_workspace\\plugins\\AutoGPT-YouTube.py', 'args': ['--search', 'try not to laugh', '--max-duration', '1', '--num-videos', '50', '--output-dir', 'videos']}

I didn't make any changes and I ran the prompts exactly the same. Anyone able to consistency get youtube plugin to work?

**Comment by jpetzke** [comment]
Try to give AutoGPT the goal to use the specific command (e.g. search_youtube) to search for xyz. That's what I use for my testing

**Comment by solo2424** [comment]
@jpetzke thanks for the suggestion. I was able to get some consistency with using the following prompt as a goal. 4 for 4 so far!
"Please use the built-in youtube plugin to search and download the videos."
